max_steps = 100

[model]
name = "meta-llama/Llama-3.2-1B"
impl = "custom"
seq_len = 128

[model.debug]
random_init = true
num_layers=3

[optim]
type = "adamw"

[data]
type = "fake"
batch_size = 1
seq_len = 128
